export const metadata = { title: "Privacy — LawNest" };

const SECTIONS = [
  {
    title: "What we collect",
    body: "Your email address, the name you give us, and the consultations you book. Nothing else. We do not ask for Aadhaar, PAN, a driving licence or any other government identifier, and we will not accept one if you send it.",
  },
  {
    title: "How you are identified",
    body: "Clients get a LawNest ID in the form LB-2026-00001. It is generated by us, means nothing outside this platform, and is safe to quote in an email to support.",
  },
  {
    title: "Sign-in",
    body: "Authentication is handled by Clerk. We never see or store your password. Verification is a one-time code sent to your email — no SMS, so nothing is tied to your phone number.",
  },
  {
    title: "Your consultation chat",
    body: "Messages in a consultation are visible to you and the assigned advocate, and are stored so both of you can come back to them. Our team can access a thread only to investigate a complaint or a payment dispute.",
  },
  {
    title: "Payments",
    body: "Consultation fees are paid by UPI directly to LawNest. We store the amount, the split between advocate and platform, and the booking it belongs to. We never store card numbers or UPI credentials.",
  },
  {
    title: "Advocates",
    body: "Advocates give us their enrolment number and practice details so we can verify them with the State Bar Council record. Verified profile details — name, court, city, practice areas, fee — are public on the platform.",
  },
  {
    title: "How advocates are ranked",
    body: "No advocate can pay to rank higher. Results are ordered by the sort you pick — rating, fee or years of experience — and by who is available, and nothing else.",
  },
  {
    title: "Deleting your data",
    body: "Write to privacy@lawnest.in from your registered email and we will delete your account, your LawNest ID and your consultation history, except records we must keep for tax and dispute purposes.",
  },
];

export default function PrivacyPage() {
  return (
    <main className="band-alt">
      <div className="container container-narrow section-tight">
        <div className="document">
          <p className="mono-label text-muted">Policy</p>
          <h1 className="mt-3 text-[2.25rem] sm:text-[2.75rem]">
            Privacy at <span className="tone-accent">LawNest</span>
          </h1>
          <p className="mt-5 leading-relaxed text-slate">
            Plain-language version. LawNest is a technology platform, not a law
            firm, and does not provide legal advice.
          </p>

          <div className="mt-9 space-y-4">
            {SECTIONS.map((s) => (
              <section key={s.title} className="card p-5">
                <h2 className="text-[1.125rem]">{s.title}</h2>
                <p className="mt-2.5 leading-relaxed text-slate">{s.body}</p>
              </section>
            ))}
          </div>

          <p className="mono-label mt-8 text-center text-muted">
            Questions · privacy@lawnest.in
          </p>
        </div>
      </div>
    </main>
  );
}
